export const Pages = {
    DUMMY_SERVER_CHECK: "DUMMY_SERVER_CHECK",
    LANDING: "LANDING",
    CREATE_INDIVIDUAL_PROFILE: "CREATE_INDIVIDUAL_PROFILE",
    INDIVIDUAL_PROFILE: "INDIVIDUAL_PROFILE",
    SCAN: "SCAN",
    SCAN_DATA: "SCAN_DATA",
};
